In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from pandas import Series, DataFrame
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
loans=pd.read_csv('lending_club_new_data.csv')

In [4]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_late_fee  \
0  27.65            0               1         3  ...                0.00   
1   1.00            0               5         3  ...                0.00   
2   8.72            0               2         2  ...                0.00   
3  20.00            0               1        10  ...               16.97   
4  11.20            0               3         9  ...                0.00   

   recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
0        0.00                     0.00           171.62          0   
1      117.08                     1.11           119.66          1   
2        0.00                     0.00           649.91          0   
3        0.00                     0.00           357.48          0   
4        0.00                     0.00           161.03          0   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 24 columns]

In [5]:
loans.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'int_rate',
       'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt', 'bad_loans',
       'emp_length_num', 'grade_num', 'sub_grade_num', 'delinq_2yrs_zero',
       'payment_inc_ratio'],
      dtype='object')

In [9]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516 entries, 0 to 9515
Data columns (total 24 columns):
loan_amnt                  9516 non-null int64
funded_amnt                9516 non-null int64
funded_amnt_inv            9516 non-null int64
int_rate                   9516 non-null float64
installment                9516 non-null float64
annual_inc                 9516 non-null int64
dti                        9516 non-null float64
delinq_2yrs                9516 non-null int64
inq_last_6mths             9516 non-null int64
open_acc                   9516 non-null int64
total_pymnt                9516 non-null float64
total_pymnt_inv            9516 non-null float64
total_rec_prncp            9516 non-null float64
total_rec_int              9516 non-null float64
total_rec_late_fee         9516 non-null float64
recoveries                 9516 non-null float64
collection_recovery_fee    9516 non-null float64
last_pymnt_amnt            9516 non-null float64
bad_loans                

In [11]:
loans['good_loans']=loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [12]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [13]:
X=loans.drop(['bad_loans','good_loans'],axis=1)

In [14]:
y=loans['good_loans']

In [15]:
print(X.shape,y.shape)

(9516, 23) (9516,)


In [16]:
xtr,xte,ytr,yte=train_test_split(X,y,test_size=0.3,random_state=124)

In [18]:
model=DecisionTreeClassifier()
model.fit(xtr,ytr)
prediction=model.predict(xte)


In [19]:
print(confusion_matrix(yte,prediction), classification_report(yte,prediction))

[[ 444   11]
 [  12 2388]]               precision    recall  f1-score   support

          no       0.97      0.98      0.97       455
         yes       1.00      0.99      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.98      0.99      0.98      2855
weighted avg       0.99      0.99      0.99      2855



In [20]:
model2=RandomForestClassifier(n_estimators=150)
model2.fit(xtr,ytr)
prediction2=model2.predict(xte)

In [21]:
print(confusion_matrix(yte,prediction2),classification_report(yte,prediction2))

[[ 442   13]
 [   0 2400]]               precision    recall  f1-score   support

          no       1.00      0.97      0.99       455
         yes       0.99      1.00      1.00      2400

    accuracy                           1.00      2855
   macro avg       1.00      0.99      0.99      2855
weighted avg       1.00      1.00      1.00      2855



In [22]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [23]:
loans.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'int_rate',
       'installment', 'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt', 'bad_loans',
       'emp_length_num', 'grade_num', 'sub_grade_num', 'delinq_2yrs_zero',
       'payment_inc_ratio', 'good_loans'],
      dtype='object')

In [24]:
X=loans.drop(['annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'bad_loans','good_loans'],axis=1)

In [25]:
y=loans['good_loans']

In [26]:
print (X.shape,y.shape)

(9516, 11) (9516,)


In [28]:
xtr,xte,ytr,yte=train_test_split(X,y,test_size=0.3,random_state=124)

In [29]:
print(xte.shape,ytr.shape)

(2855, 11) (6661,)


In [30]:
model3=DecisionTreeClassifier()
model3.fit(xtr,ytr)
prediction3=model3.predict(xte)

In [31]:
print(confusion_matrix(yte,prediction3))

[[ 301  154]
 [ 160 2240]]


In [32]:
print(classification_report(yte,prediction3))

              precision    recall  f1-score   support

          no       0.65      0.66      0.66       455
         yes       0.94      0.93      0.93      2400

    accuracy                           0.89      2855
   macro avg       0.79      0.80      0.80      2855
weighted avg       0.89      0.89      0.89      2855



In [39]:
#random_forest

In [34]:
model4=RandomForestClassifier(n_estimators=150)

In [35]:
model4.fit(xtr,ytr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
prediction4=model4.predict(xte)

In [37]:
print(confusion_matrix(yte,prediction4))

[[ 283  172]
 [  73 2327]]


In [38]:
print(classification_report(yte,prediction4))

              precision    recall  f1-score   support

          no       0.79      0.62      0.70       455
         yes       0.93      0.97      0.95      2400

    accuracy                           0.91      2855
   macro avg       0.86      0.80      0.82      2855
weighted avg       0.91      0.91      0.91      2855

