In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
from sklearn import datasets


In [5]:
iris=datasets.load_iris()

In [6]:
X=iris.data

In [7]:
y=iris.target

In [8]:
X.shape

(150, 4)

In [9]:
y.shape

(150,)

In [10]:
iris=pd.DataFrame(X,columns=iris.feature_names)


In [11]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
#text analysis

In [13]:
train_text=['go home tonight','go take a cab','soccer! go play soccer...']

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
vector=CountVectorizer()

In [16]:
vector.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [17]:
vector.get_feature_names()

['cab', 'go', 'home', 'play', 'soccer', 'take', 'tonight']

In [18]:
train_text_dtmatrix=vector.transform(train_text)

In [19]:
train_text_dtmatrix

<3x7 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [20]:
train_text_dtmatrix.toarray()

array([[0, 1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 2, 0, 0]], dtype=int64)

In [21]:
text=pd.DataFrame(train_text_dtmatrix.toarray(),columns=vector.get_feature_names())

In [22]:
text.head()

cab  go  home  play  soccer  take  tonight
0    0   1     1     0       0     0        1
1    1   1     0     0       0     1        0
2    0   1     0     1       2     0        0

In [23]:
train_text

['go home tonight', 'go take a cab', 'soccer! go play soccer...']

In [24]:
 type(train_text_dtmatrix)

scipy.sparse.csr.csr_matrix

In [28]:
print (train_text_dtmatrix)

  (0, 1)	1
  (0, 2)	1
  (0, 6)	1
  (1, 0)	1
  (1, 1)	1
  (1, 5)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	2


In [29]:
test_text=["soccer don't play go"]

In [31]:
test_text_dtmatrix=vector.transform(test_text)

In [32]:
test_text_dtmatrix.toarray()

array([[0, 1, 0, 1, 1, 0, 0]], dtype=int64)

In [33]:
pd.DataFrame(test_text_dtmatrix.toarray(), columns=vector.get_feature_names())

cab  go  home  play  soccer  take  tonight
0    0   1     0     1       1     0        0

In [41]:
test_text=["soccer? don't play just go home",\
      "hey, i hope to see you all in the soccer game",\
      "The game was awesome, he scored at the end and won",\
      "the game was awesome, he scored at the end, won and off to home"]

In [42]:
test_text_dtmatrix=vector.transform(test_text)

In [43]:
test_text_dtmatrix.toarray()

array([[0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [45]:
pd.DataFrame(test_text_dtmatrix.toarray(),columns=vector.get_feature_names())

cab  go  home  play  soccer  take  tonight
0    0   1     1     1       1     0        0
1    0   0     0     0       1     0        0
2    0   0     0     0       0     0        0
3    0   0     1     0       0     0        0

In [46]:
test_text

["soccer? don't play just go home",
 'hey, i hope to see you all in the soccer game',
 'The game was awesome, he scored at the end and won',
 'the game was awesome, he scored at the end, won and off to home']